### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by doczoidberg** [Kitware/visualizer#13]
I have few questions:

1. does this code work with older paraview installations (5.0)? As far as I can see this is a rewrite on client with react+redux instead of jquery?

2. is this production ready?

3. (crosspost from mailing) The web visuailzer should work via npm installation? It does not work for me:

```
C:\Users\danie\AppData\Roaming\npm\node_modules\pvw-visualizer\bin\pvw-visualizer-cli.js:41
var pvPythonExecs = find(paraview).filter(function(file) { return file.match(/pvpython$/) || file.match(/pvpython.exe$/); });
                                   ^

TypeError: find(...).filter is not a function
    at Object.<anonymous> (C:\Users\danie\AppData\Roaming\npm\node_modules\pvw-visualizer\bin\pvw-visualizer-cli.js:41:36)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by jourdain** [comment]
1) Mostly yes, but the client is expecting new RPC endpoints that are only present in Paraview/master and the next release (5.2). 

2) Almost/yes as we don't expect to add or fix anything as far as we know. May still have a couple small bug fix.

3) It should, but we never run it on Windows, and until we bring back ParaViewWeb support in our binaries with Windows, it won't be easy to test. This should happen for the 5.2 release though.
That command line is just hiding the pvpython one. (See mailing list)

**Comment by doczoidberg** [comment]
1) so it does not work with PV 5.0?

**Comment by jourdain** [comment]
It won't fully work (missing color opacity handling) and you will run into performance issue (binary image stream as been improved).

5.2 fix all of those issues.
